---
- name: Installing Pod network on cluster
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Recreating all pods to register with the new pod network
  become_user: "{{ ansible_user }}"
  shell: "for ns in $(kubectl get ns -o name | cut -f2 -d'/'); do kubectl delete pods -n $ns --all; done"
