---
- name: Installing flannel pod network on cluster
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Starting kubelet
  service:
    name: kubelet
    state: started
