---
- name: Deleting /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: absent

- name: Running ifconfig flannel.1 down
  shell: "ifconfig flannel.1 down"

- name: Running ip link delete flannel
  shell: "ip link delete flannel.1"

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Starting kubelet
  service:
    name: kubelet
    state: started
