---
- name: Deleting CNI binary
  shell: "rm -f /opt/cni/bin/flannel*"
  args:
    warn: no

- name: Deleting /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: absent

- name: Running ifconfig flannel.1 down
  shell: "ifconfig flannel.1 down"

- name: Running ip link delete flannel
  shell: "ip link delete flannel.1"

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Cleaning up iptables rules
  shell: "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"

- name: Resetting the IPVS tables
  shell: "ipvsadm -C"

- name: Starting kubelet
  service:
    name: kubelet
    state: started

- name: Running systemctl daemon-reload
  shell: "systemctl daemon-reload"
