---
- name: Create /boot/firmware directory
  file:
    path: /boot/firmware
    state: directory

- name: Enable cgroup memory
  template:
    src: cmdline
    dest: '/boot/firmware/cmdline.txt'
  when: ansible_distribution == 'Ubuntu'

- name: Reboot the machines
  reboot:
    reboot_timeout: 120

- name: Waiting for server to come back up
  local_action: wait_for host="{{ inventory_hostname_short }}" port=22 state=started
