---
- hosts: all
  become: true
  gather_facts: true
  serial: 1

  vars_files:
    - group_vars/all

  roles:
    - { role: install, tags: install }
    - { role: system, tags: system }
    - { role: upgrade, tags: upgrade }
    - { role: uninstall, tags: uninstall }
