---
- name: Copy canal.yaml to /etc/kubernetes
  template:
    src: arm64/canal.yaml
    dest: '/etc/kubernetes/canal.yaml'

- name: Installing canal pod network on cluster
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f /etc/kubernetes/canal.yaml

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Starting kubelet
  service:
    name: kubelet
    state: started
