---
- name: Get architecture
  shell: uname -m
  register: architecture

- name: Copy x86-64/canal.yaml to /etc/kubernetes
  template:
    src: x86-64/canal.yaml
    dest: '/etc/kubernetes/canal.yaml'
  when: architecture.stdout == 'x86_64'

- name: Copy arm64/canal.yaml to /etc/kubernetes
  template:
    src: arm64/canal.yaml
    dest: '/etc/kubernetes/canal.yaml'
  when: architecture.stdout == 'arm64'

- name: Installing canal pod network on cluster
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f /etc/kubernetes/canal.yaml

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Starting kubelet
  service:
    name: kubelet
    state: started
