---
- name: Deleting /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: absent

- name: Running ifdown weave
  shell: "ifconfig weave down"

- name: Running ip link delete weave
  shell: "ip link delete weave"

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Starting kubelet
  service:
    name: kubelet
    state: started
