---
- hosts: masters
  become: true

  vars_files:
    - group_vars/all

  roles:
    # Need to get all ips of hosts and run it from control machine to drain all nodes
    - { role: reset, tags: reset }

- hosts: all
  become: true

  vars_files:
    - group_vars/all

  roles:
    - { role: uninstall, tags: uninstall }
