---
- hosts: all
  become: true

  vars_files:
    - group_vars/all

  roles:
    - { role: install, tags: install }
    - { role: endpoint, tags: endpoint }

- hosts: masters
  become: true

  vars_files:
    - group_vars/all

  roles:
    - { role: system, tags: system }
    - { role: kubeadm, tags: kubeadm }
    - { role: weave-net, tags: weave_net }

- hosts: masters
  become: true

  vars_files:
    - group_vars/all

  roles:
    - { role: generate_tokens, tags: generate_tokens }

- hosts: slaves
  become: true

  vars_files:
    - group_vars/all

  roles:
    - { role: join_node, tags: join_node }

- hosts: all
  become: true
  serial: 1

  vars_files:
    - group_vars/all

  roles:
    - { role: upgrade, tags: upgrade }
    - { role: reset, tags: reset }
    - { role: uninstall, tags: uninstall }
