---
- name: Deleting /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: absent

- name: Stopping kubelet
  service:
    name: kubelet
    state: stopped

- name: Starting kubelet
  service:
    name: kubelet
    state: started
