---
- hosts: all
  become: true
  serial: 1

  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Installing necessary packages
      apt:
        pkg:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'software-properties-common'
          - 'gnupg2'
          - 'vim'
          - 'curl'
          - 'bash-completion'
          - 'net-tools'
          - 'ipvsadm'
        state: latest
