---
- hosts: all
  become: true

  tasks:
    - name: Set system hostname
      hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Reboot the machines
      reboot:
        reboot_timeout: 120

    - name: Waiting for server to come back up
      local_action: wait_for host="{{ inventory_hostname_short }}" port=22 state=started
